### PR TITLE
Help Menu Bugs

### LINKED ISSUE #160: Help Bugs
1. If there is a typo in the command flag like
`help /exercs 1`, it prints nothing.

2. formatting of `help /exercise`, `help /workout` and `help /program`

3. could we standardize listing format? 
- help uses (1) list item
- everything else uses 1.

### PR DESCRIPTION
**Pull request by LWachtel1**
Fixes #160 

image

image

### CODE REVIEW

File: src/main/java/byteceps/processing/HelpMenuManager.java [hunk 1]
```diff
@@ -78,7 +78,7 @@ private String generateAllActions(String command) throws Exceptions.InvalidInput
         for (String flagFunction : flagFunctions) {
             result.append(String.format(HelpStrings.HELP_LIST_ITEM, flagFunction, System.lineSeparator()));
         }
-        result.delete(0, 4); //remove the first 3 tabs
+        result.delete(0, 13); //remove the first 12 whitespace characters
```
Comment (joshualeejunyi) [inline src/main/java/byteceps/processing/HelpMenuManager.java:81]: Why remove the first 12 whitespace characters? Is it possible to remove the whitespace from HELP_LIST_ITEM or use `\t` to tab it?

Comment (LWachtel1) [reply src/main/java/byteceps/processing/HelpMenuManager.java:81]: I replaced 3 tabs with 12 whitespace characters. I think _"\t"_ usage was causing the indentation issue because I believe the number of whitespace chars within tab varies depending on whether you use CMD or terminal, etc. So using a fixed number of whitespace characters is more consistent

Comment (LWachtel1) [reply src/main/java/byteceps/processing/HelpMenuManager.java:81]: Also, I believe another teammate implemented result.delete(...) as the first bullet point is in line with [BYTE-CEPS] so it requires no such indentation

**Review by joshualeejunyi — APPROVED** [review]
