### PR TITLE
Bug fix for invalid date & future dates

### LINKED ISSUE #117: [PE-D][Tester B] Should not be able to log dates into the future
Able to log dates into October of this year even though it is not this date yet

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: JustinSoh/ped#5

### LINKED ISSUE #120: [PE-D][Tester B] No day number 31 on feburary
This is a bug. Should not be able to log a day that doesn't exist

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: JustinSoh/ped#6

### PR DESCRIPTION
**Pull request by V4Vern**
fixes #117 
fixes #120

### CODE REVIEW

File: src/main/java/byteceps/processing/WeeklyProgramManager.java [hunk 1]
```diff
@@ -208,25 +208,40 @@ private String executeLogAction(Parser parser)
...
 
+    private boolean isValidDate(String date) {
+        try {
+            LocalDate.parse(date);
+            return true;
+        } catch (DateTimeParseException e) {
+            return false;
+        }
+    }
+
```
Comment (LWachtel1) [inline src/main/java/byteceps/processing/WeeklyProgramManager.java:244]: Effective bug fix

**Review by LWachtel1 — COMMENTED** [review]
LGTM
